class AppStrings {
  static Map<String, Map<String, String>> translations = {
    // Navigation
    'home': {
      'en': 'Home',
      'hi': 'होम',
      'mr': 'मुख्यपृष्ठ',
      'ta': 'முகப்பு',
    },
    'services': {
      'en': 'Services',
      'hi': 'सेवाएं',
      'mr': 'सेवा',
      'ta': 'சேவைகள்',
    },
    'documents': {
      'en': 'Documents',
      'hi': 'दस्तावेज़',
      'mr': 'कागदपत्रे',
      'ta': 'ஆவணங்கள்',
    },
    'voice_ai': {
      'en': 'Voice AI',
      'hi': 'वॉयस AI',
      'mr': 'व्हॉइस AI',
      'ta': 'குரல் AI',
    },
    'profile': {
      'en': 'Profile',
      'hi': 'प्रोफ़ाइल',
      'mr': 'प्रोफाइल',
      'ta': 'சுயவிவரம்',
    },

    // Login Screen
    'welcome_back': {
      'en': 'Welcome Back',
      'hi': 'वापसी पर स्वागत है',
      'mr': 'परत स्वागत आहे',
      'ta': 'மீண்டும் வரவேற்கிறோம்',
    },
    'login_subtitle': {
      'en': 'Login to access your civic services',
      'hi': 'अपनी नागरिक सेवाओं तक पहुंचने के लिए लॉगिन करें',
      'mr': 'आपल्या नागरी सेवांमध्ये प्रवेश करण्यासाठी लॉगिन करा',
      'ta': 'உங்கள் குடிமை சேவைகளை அணுக உள்நுழையவும்',
    },
    'email_or_phone': {
      'en': 'Email or Phone',
      'hi': 'ईमेल या फ़ोन',
      'mr': 'ईमेल किंवा फोन',
      'ta': 'மின்னஞ்சல் அல்லது தொலைபேசி',
    },
    'password': {
      'en': 'Password',
      'hi': 'पासवर्ड',
      'mr': 'पासवर्ड',
      'ta': 'கடவுச்சொல்',
    },
    'forgot_password': {
      'en': 'Forgot Password?',
      'hi': 'पासवर्ड भूल गए?',
      'mr': 'पासवर्ड विसरलात?',
      'ta': 'கடவுச்சொல் மறந்துவிட்டதா?',
    },
    'login': {
      'en': 'Login',
      'hi': 'लॉगिन',
      'mr': 'लॉगिन',
      'ta': 'உள்நுழை',
    },
    'or': {
      'en': 'OR',
      'hi': 'या',
      'mr': 'किंवा',
      'ta': 'அல்லது',
    },
    'google': {
      'en': 'Google',
      'hi': 'गूगल',
      'mr': 'गूगल',
      'ta': 'கூகுள்',
    },
    'otp': {
      'en': 'OTP',
      'hi': 'OTP',
      'mr': 'OTP',
      'ta': 'OTP',
    },
    'no_account': {
      'en': "Don't have an account? ",
      'hi': 'खाता नहीं है? ',
      'mr': 'खाते नाही? ',
      'ta': 'கணக்கு இல்லையா? ',
    },
    'register': {
      'en': 'Register',
      'hi': 'रजिस्टर करें',
      'mr': 'नोंदणी करा',
      'ta': 'பதிவு செய்யுங்கள்',
    },
    'continue_as_guest': {
      'en': 'Continue as Guest',
      'hi': 'अतिथि के रूप में जारी रखें',
      'mr': 'अतिथी म्हणून सुरू ठेवा',
      'ta': 'விருந்தினராக தொடரவும்',
    },
    'limited_features': {
      'en': 'Limited features available',
      'hi': 'सीमित सुविधाएं उपलब्ध',
      'mr': 'मर्यादित वैशिष्ट्ये उपलब्ध',
      'ta': 'வரையறுக்கப்பட்ட அம்சங்கள் கிடைக்கும்',
    },
    'select_language': {
      'en': 'Select Language',
      'hi': 'भाषा चुनें',
      'mr': 'भाषा निवडा',
      'ta': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    },

    // Dashboard
    'hi_greeting': {
      'en': 'Hi! 👋',
      'hi': 'नमस्ते! 👋',
      'mr': 'नमस्कार! 👋',
      'ta': 'வணக்கம்! 👋',
    },
    'how_can_help': {
      'en': 'How can I help you today?',
      'hi': 'आज मैं आपकी कैसे मदद कर सकता हूं?',
      'mr': 'आज मी तुम्हाला कशी मदत करू शकतो?',
      'ta': 'இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?',
    },
    'queries': {
      'en': 'Queries',
      'hi': 'प्रश्न',
      'mr': 'प्रश्न',
      'ta': 'கேள்விகள்',
    },
    'pending': {
      'en': 'Pending',
      'hi': 'लंबित',
      'mr': 'प्रलंबित',
      'ta': 'நிலுவையில்',
    },
    'avg_time': {
      'en': 'Avg Time',
      'hi': 'औसत समय',
      'mr': 'सरासरी वेळ',
      'ta': 'சராசரி நேரம்',
    },
    'success': {
      'en': 'Success',
      'hi': 'सफलता',
      'mr': 'यश',
      'ta': 'வெற்றி',
    },
    'quick_services': {
      'en': 'Quick Services',
      'hi': 'त्वरित सेवाएं',
      'mr': 'द्रुत सेवा',
      'ta': 'விரைவு சேவைகள்',
    },
    'view_all': {
      'en': 'View All',
      'hi': 'सभी देखें',
      'mr': 'सर्व पहा',
      'ta': 'அனைத்தையும் காண்க',
    },
    'recent_conversation': {
      'en': 'Recent Conversation',
      'hi': 'हाल की बातचीत',
      'mr': 'अलीकडील संभाषण',
      'ta': 'சமீபத்திய உரையாடல்',
    },
    'no_conversation': {
      'en': 'No conversation yet',
      'hi': 'अभी तक कोई बातचीत नहीं',
      'mr': 'अद्याप संभाषण नाही',
      'ta': 'இதுவரை உரையாடல் இல்லை',
    },
    'start_conversation': {
      'en': 'Start a conversation with CVI',
      'hi': 'CVI के साथ बातचीत शुरू करें',
      'mr': 'CVI सह संभाषण सुरू करा',
      'ta': 'CVI உடன் உரையாடலைத் தொடங்குங்கள்',
    },
    'continue_conversation': {
      'en': 'Continue Conversation',
      'hi': 'बातचीत जारी रखें',
      'mr': 'संभाषण सुरू ठेवा',
      'ta': 'உரையாடலைத் தொடரவும்',
    },
    'recent_activity': {
      'en': 'Recent Activity',
      'hi': 'हाल की गतिविधि',
      'mr': 'अलीकडील क्रियाकलाप',
      'ta': 'சமீபத்திய செயல்பாடு',
    },
    'ask_cvi': {
      'en': 'Ask CVI',
      'hi': 'CVI से पूछें',
      'mr': 'CVI ला विचारा',
      'ta': 'CVI கேளுங்கள்',
    },

    // Services
    'all_services': {
      'en': 'All Services',
      'hi': 'सभी सेवाएं',
      'mr': 'सर्व सेवा',
      'ta': 'அனைத்து சேவைகள்',
    },
    'search_services': {
      'en': 'Search services...',
      'hi': 'सेवाएं खोजें...',
      'mr': 'सेवा शोधा...',
      'ta': 'சேவைகளைத் தேடு...',
    },
    'all': {
      'en': 'All',
      'hi': 'सभी',
      'mr': 'सर्व',
      'ta': 'அனைத்தும்',
    },
    'identity': {
      'en': 'Identity',
      'hi': 'पहचान',
      'mr': 'ओळख',
      'ta': 'அடையாளம்',
    },
    'finance': {
      'en': 'Finance',
      'hi': 'वित्त',
      'mr': 'वित्त',
      'ta': 'நிதி',
    },
    'property': {
      'en': 'Property',
      'hi': 'संपत्ति',
      'mr': 'मालमत्ता',
      'ta': 'சொத்து',
    },
    'education': {
      'en': 'Education',
      'hi': 'शिक्षा',
      'mr': 'शिक्षण',
      'ta': 'கல்வி',
    },
    'medical': {
      'en': 'Medical',
      'hi': 'चिकित्सा',
      'mr': 'वैद्यकीय',
      'ta': 'மருத்துவம்',
    },
    'welfare': {
      'en': 'Welfare',
      'hi': 'कल्याण',
      'mr': 'कल्याण',
      'ta': 'நலன்புரி',
    },
    'transport': {
      'en': 'Transport',
      'hi': 'परिवहन',
      'mr': 'वाहतूक',
      'ta': 'போக்குவரத்து',
    },
    'legal': {
      'en': 'Legal',
      'hi': 'कानूनी',
      'mr': 'कायदेशीर',
      'ta': 'சட்டம்',
    },

    // Documents
    'my_documents': {
      'en': 'My Documents',
      'hi': 'मेरे दस्तावेज़',
      'mr': 'माझी कागदपत्रे',
      'ta': 'என் ஆவணங்கள்',
    },
    'documents_stored': {
      'en': 'documents stored',
      'hi': 'दस्तावेज़ संग्रहीत',
      'mr': 'कागदपत्रे संग्रहित',
      'ta': 'ஆவணங்கள் சேமிக்கப்பட்டன',
    },
    'all_documents': {
      'en': 'All Documents',
      'hi': 'सभी दस्तावेज़',
      'mr': 'सर्व कागदपत्रे',
      'ta': 'அனைத்து ஆவணங்கள்',
    },
    'upload': {
      'en': 'Upload',
      'hi': 'अपलोड',
      'mr': 'अपलोड',
      'ta': 'பதிவேற்று',
    },
    'archived': {
      'en': 'Archived',
      'hi': 'संग्रहीत',
      'mr': 'संग्रहित',
      'ta': 'காப்பகப்படுத்தப்பட்டது',
    },
    'upload_documents': {
      'en': 'Upload Documents',
      'hi': 'दस्तावेज़ अपलोड करें',
      'mr': 'कागदपत्रे अपलोड करा',
      'ta': 'ஆவணங்களைப் பதிவேற்றவும்',
    },
    'drag_drop': {
      'en': 'Drag & drop files here or click to browse',
      'hi': 'फ़ाइलें यहां खींचें और छोड़ें या ब्राउज़ करने के लिए क्लिक करें',
      'mr': 'फाइल्स येथे ड्रॅग आणि ड्रॉप करा किंवा ब्राउझ करण्यासाठी क्लिक करा',
      'ta': 'கோப்புகளை இங்கே இழுத்து விடுங்கள் அல்லது உலாவ கிளிக் செய்யவும்',
    },
    'choose_files': {
      'en': 'Choose Files',
      'hi': 'फ़ाइलें चुनें',
      'mr': 'फाइल्स निवडा',
      'ta': 'கோப்புகளைத் தேர்ந்தெடுக்கவும்',
    },
    'supported_formats': {
      'en': 'Supported Formats',
      'hi': 'समर्थित प्रारूप',
      'mr': 'समर्थित स्वरूप',
      'ta': 'ஆதரிக்கப்படும் வடிவங்கள்',
    },
    'no_archived': {
      'en': 'No Archived Documents',
      'hi': 'कोई संग्रहीत दस्तावेज़ नहीं',
      'mr': 'संग्रहित कागदपत्रे नाहीत',
      'ta': 'காப்பகப்படுத்தப்பட்ட ஆவணங்கள் இல்லை',
    },
    'archived_appear': {
      'en': 'Archived documents will appear here',
      'hi': 'संग्रहीत दस्तावेज़ यहां दिखाई देंगे',
      'mr': 'संग्रहित कागदपत्रे येथे दिसतील',
      'ta': 'காப்பகப்படுத்தப்பட்ட ஆவணங்கள் இங்கே தோன்றும்',
    },
    'verified': {
      'en': 'Verified',
      'hi': 'सत्यापित',
      'mr': 'सत्यापित',
      'ta': 'சரிபார்க்கப்பட்டது',
    },

    // Profile
    'account_settings': {
      'en': 'Account Settings',
      'hi': 'खाता सेटिंग्स',
      'mr': 'खाते सेटिंग्ज',
      'ta': 'கணக்கு அமைப்புகள்',
    },
    'personal_info': {
      'en': 'Personal Information',
      'hi': 'व्यक्तिगत जानकारी',
      'mr': 'वैयक्तिक माहिती',
      'ta': 'தனிப்பட்ட தகவல்',
    },
    'security_privacy': {
      'en': 'Security & Privacy',
      'hi': 'सुरक्षा और गोपनीयता',
      'mr': 'सुरक्षा आणि गोपनीयता',
      'ta': 'பாதுகாப்பு & தனியுரிமை',
    },
    'notifications': {
      'en': 'Notifications',
      'hi': 'सूचनाएं',
      'mr': 'सूचना',
      'ta': 'அறிவிப்புகள்',
    },
    'preferences': {
      'en': 'Preferences',
      'hi': 'प्राथमिकताएं',
      'mr': 'प्राधान्ये',
      'ta': 'விருப்பங்கள்',
    },
    'language': {
      'en': 'Language',
      'hi': 'भाषा',
      'mr': 'भाषा',
      'ta': 'மொழி',
    },
    'dark_mode': {
      'en': 'Dark Mode',
      'hi': 'डार्क मोड',
      'mr': 'डार्क मोड',
      'ta': 'இருண்ட பயன்முறை',
    },
    'support': {
      'en': 'Support',
      'hi': 'सहायता',
      'mr': 'समर्थन',
      'ta': 'ஆதரவு',
    },
    'help_faq': {
      'en': 'Help & FAQ',
      'hi': 'सहायता और FAQ',
      'mr': 'मदत आणि FAQ',
      'ta': 'உதவி & கேள்வி பதில்',
    },
    'send_feedback': {
      'en': 'Send Feedback',
      'hi': 'प्रतिक्रिया भेजें',
      'mr': 'अभिप्राय पाठवा',
      'ta': 'கருத்து அனுப்புங்கள்',
    },
    'about_cvi': {
      'en': 'About CVI',
      'hi': 'CVI के बारे में',
      'mr': 'CVI बद्दल',
      'ta': 'CVI பற்றி',
    },
    'logout': {
      'en': 'Logout',
      'hi': 'लॉगआउट',
      'mr': 'लॉगआउट',
      'ta': 'வெளியேறு',
    },
    'applications': {
      'en': 'Applications',
      'hi': 'आवेदन',
      'mr': 'अर्ज',
      'ta': 'விண்ணப்பங்கள்',
    },
    'completed': {
      'en': 'Completed',
      'hi': 'पूर्ण',
      'mr': 'पूर्ण',
      'ta': 'முடிந்தது',
    },
    'enter_email_password': {
      'en': 'Please enter email and password',
      'hi': 'कृपया ईमेल और पासवर्ड दर्ज करें',
      'mr': 'कृपया ईमेल आणि पासवर्ड प्रविष्ट करा',
      'ta': 'மின்னஞ்சல் மற்றும் கடவுச்சொல்லை உள்ளிடவும்',
    },
    'login_failed': {
      'en': 'Login failed',
      'hi': 'लॉगिन विफल',
      'mr': 'लॉगिन अयशस्वी',
      'ta': 'உள்நுழைவு தோல்வியடைந்தது',
    },
    'logging_in': {
      'en': 'Logging in...',
      'hi': 'लॉगिन हो रहा है...',
      'mr': 'लॉगिन करत आहे...',
      'ta': 'உள்நுழைகிறது...',
    },
    'agree_terms': {
      'en': 'Please agree to Terms & Conditions',
      'hi': 'कृपया नियम और शर्तें स्वीकार करें',
      'mr': 'कृपया अटी व शर्ती मान्य करा',
      'ta': 'விதிமுறைகள் மற்றும் நிபந்தனைகளை ஏற்கவும்',
    },
    'passwords_mismatch': {
      'en': 'Passwords do not match',
      'hi': 'पासवर्ड मेल नहीं खाते',
      'mr': 'पासवर्ड जुळत नाहीत',
      'ta': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    },
    'registration_failed': {
      'en': 'Registration failed',
      'hi': 'पंजीकरण विफल',
      'mr': 'नोंदणी अयशस्वी',
      'ta': 'பதிவு தோல்வியடைந்தது',
    },

    // Common
    'search': {
      'en': 'Search',
      'hi': 'खोजें',
      'mr': 'शोधा',
      'ta': 'தேடு',
    },
    'cancel': {
      'en': 'Cancel',
      'hi': 'रद्द करें',
      'mr': 'रद्द करा',
      'ta': 'ரத்து செய்',
    },
    'save': {
      'en': 'Save',
      'hi': 'सहेजें',
      'mr': 'जतन करा',
      'ta': 'சேமி',
    },
    'delete': {
      'en': 'Delete',
      'hi': 'हटाएं',
      'mr': 'हटवा',
      'ta': 'நீக்கு',
    },
    'edit': {
      'en': 'Edit',
      'hi': 'संपादित करें',
      'mr': 'संपादित करा',
      'ta': 'திருத்து',
    },
    'close': {
      'en': 'Close',
      'hi': 'बंद करें',
      'mr': 'बंद करा',
      'ta': 'மூடு',
    },
    'submit': {
      'en': 'Submit',
      'hi': 'जमा करें',
      'mr': 'सबमिट करा',
      'ta': 'சமர்ப்பி',
    },
    'apply_now': {
      'en': 'Apply Now',
      'hi': 'अभी आवेदन करें',
      'mr': 'आता अर्ज करा',
      'ta': 'இப்போது விண்ணப்பிக்கவும்',
    },
    'learn_more': {
      'en': 'Learn More',
      'hi': 'और जानें',
      'mr': 'अधिक जाणून घ्या',
      'ta': 'மேலும் அறிக',
    },
    'processing_time': {
      'en': 'Processing Time',
      'hi': 'प्रसंस्करण समय',
      'mr': 'प्रक्रिया वेळ',
      'ta': 'செயலாக்க நேரம்',
    },
    'required_documents': {
      'en': 'Required Documents',
      'hi': 'आवश्यक दस्तावेज़',
      'mr': 'आवश्यक कागदपत्रे',
      'ta': 'தேவையான ஆவணங்கள்',
    },
    'eligibility': {
      'en': 'Eligibility',
      'hi': 'पात्रता',
      'mr': 'पात्रता',
      'ta': 'தகுதி',
    },
    'official_website': {
      'en': 'Official Website',
      'hi': 'आधिकारिक वेबसाइट',
      'mr': 'अधिकृत वेबसाइट',
      'ta': 'அதிகாரப்பூர்வ வலைத்தளம்',
    },

    // Service Names
    'aadhaar_card': {
      'en': 'Aadhaar Card',
      'hi': 'आधार कार्ड',
      'mr': 'आधार कार्ड',
      'ta': 'ஆதார் அட்டை',
    },
    'pan_card': {
      'en': 'PAN Card',
      'hi': 'पैन कार्ड',
      'mr': 'पॅन कार्ड',
      'ta': 'PAN அட்டை',
    },
    'ration_card': {
      'en': 'Ration Card',
      'hi': 'राशन कार्ड',
      'mr': 'रेशन कार्ड',
      'ta': 'ரேஷன் அட்டை',
    },
    'senior_pension': {
      'en': 'Senior Citizen Pension',
      'hi': 'वरिष्ठ नागरिक पेंशन',
      'mr': 'ज्येष्ठ नागरिक निवृत्तीवेतन',
      'ta': 'மூத்த குடிமக்கள் ஓய்வூதியம்',
    },
    'birth_certificate': {
      'en': 'Birth Certificate',
      'hi': 'जन्म प्रमाण पत्र',
      'mr': 'जन्म दाखला',
      'ta': 'பிறப்புச் சான்றிதழ்',
    },
    'land_records': {
      'en': 'Land Records',
      'hi': 'भूमि रिकॉर्ड',
      'mr': 'जमीन नोंदी',
      'ta': 'நில பதிவுகள்',
    },
    'passport': {
      'en': 'Passport',
      'hi': 'पासपोर्ट',
      'mr': 'पारपत्र',
      'ta': 'கடவுச்சீட்டு',
    },
    'driving_license': {
      'en': 'Driving License',
      'hi': 'ड्राइविंग लाइसेंस',
      'mr': 'वाहन चालक परवाना',
      'ta': 'ஓட்டுநர் உரிமம்',
    },

    // Service Descriptions
    'aadhaar_desc': {
      'en': 'Apply for or update your Aadhaar card',
      'hi': 'अपने आधार कार्ड के लिए आवेदन करें या अपडेट करें',
      'mr': 'आपल्या आधार कार्डसाठी अर्ज करा किंवा अद्यतनित करा',
      'ta': 'உங்கள் ஆதார் அட்டையை விண்ணப்பிக்கவும் அல்லது புதுப்பிக்கவும்',
    },
    'pan_desc': {
      'en': 'Get your Permanent Account Number',
      'hi': 'अपना स्थायी खाता संख्या प्राप्त करें',
      'mr': 'तुमचा कायमस्वरूपी खाते क्रमांक मिळवा',
      'ta': 'உங்கள் நிரந்தர கணக்கு எண்ணைப் பெறுங்கள்',
    },
    'ration_desc': {
      'en': 'Apply for subsidized food grains',
      'hi': 'सब्सिडी वाले खाद्यान्न के लिए आवेदन करें',
      'mr': 'अनुदानित धान्यासाठी अर्ज करा',
      'ta': 'மானிய உணவு தானியங்களுக்கு விண்ணப்பிக்கவும்',
    },
    'senior_pension_desc': {
      'en': 'Monthly pension for senior citizens',
      'hi': 'वरिष्ठ नागरिकों के लिए मासिक पेंशन',
      'mr': 'ज्येष्ठ नागरिकांसाठी मासिक निवृत्तीवेतन',
      'ta': 'மூத்த குடிமக்களுக்கான மாதாந்திர ஓய்வூதியம்',
    },
    'birth_certificate_desc': {
      'en': 'Official birth registration certificate',
      'hi': 'आधिकारिक जन्म पंजीकरण प्रमाण पत्र',
      'mr': 'अधिकृत जन्म नोंदणी प्रमाणपत्र',
      'ta': 'அதிகாரப்பூர்வ பிறப்பு பதிவு சான்றிதழ்',
    },
    'land_records_desc': {
      'en': 'Access and verify land ownership',
      'hi': 'भूमि स्वामित्व की पहुंच और सत्यापन',
      'mr': 'जमीन मालकीचा प्रवेश आणि पडताळणी',
      'ta': 'நில உரிமையை அணுகவும் சரிபார்க்கவும்',
    },
    'passport_desc': {
      'en': 'Apply for Indian passport',
      'hi': 'भारतीय पासपोर्ट के लिए आवेदन करें',
      'mr': 'भारतीय पारपत्रासाठी अर्ज करा',
      'ta': 'இந்திய கடவுச்சீட்டுக்கு விண்ணப்பிக்கவும்',
    },
    'driving_license_desc': {
      'en': 'Get your driving license',
      'hi': 'अपना ड्राइविंग लाइसेंस प्राप्त करें',
      'mr': 'तुमचा वाहन चालक परवाना मिळवा',
      'ta': 'உங்கள் ஓட்டுநர் உரிமத்தைப் பெறுங்கள்',
    },

    // Voice AI Screen
    'voice_assistant': {
      'en': 'Voice Assistant',
      'hi': 'वॉयस असिस्टेंट',
      'mr': 'व्हॉइस असिस्टंट',
      'ta': 'குரல் உதவியாளர்',
    },
    'listening': {
      'en': 'Listening...',
      'hi': 'सुन रहा हूं...',
      'mr': 'ऐकत आहे...',
      'ta': 'கேட்கிறேன்...',
    },
    'speak_now': {
      'en': 'Speak now',
      'hi': 'अब बोलें',
      'mr': 'आता बोला',
      'ta': 'இப்போது பேசுங்கள்',
    },
    'tap_to_speak': {
      'en': 'Tap to speak',
      'hi': 'बोलने के लिए टैप करें',
      'mr': 'बोलण्यासाठी टॅप करा',
      'ta': 'பேச தட்டவும்',
    },
    'processing': {
      'en': 'Processing...',
      'hi': 'प्रोसेस हो रहा है...',
      'mr': 'प्रक्रिया करत आहे...',
      'ta': 'செயலாக்கப்படுகிறது...',
    },
    'type_message': {
      'en': 'Type your message...',
      'hi': 'अपना संदेश टाइप करें...',
      'mr': 'तुमचा संदेश टाइप करा...',
      'ta': 'உங்கள் செய்தியை தட்டச்சு செய்யவும்...',
    },
    'send': {
      'en': 'Send',
      'hi': 'भेजें',
      'mr': 'पाठवा',
      'ta': 'அனுப்பு',
    },
    'conversation_history': {
      'en': 'Conversation History',
      'hi': 'बातचीत का इतिहास',
      'mr': 'संभाषण इतिहास',
      'ta': 'உரையாடல் வரலாறு',
    },
    'clear_conversation': {
      'en': 'Clear Conversation',
      'hi': 'बातचीत साफ़ करें',
      'mr': 'संभाषण साफ करा',
      'ta': 'உரையாடலை அழிக்கவும்',
    },
    'no_messages': {
      'en': 'No messages yet',
      'hi': 'अभी तक कोई संदेश नहीं',
      'mr': 'अद्याप कोणतेही संदेश नाहीत',
      'ta': 'இதுவரை செய்திகள் இல்லை',
    },
    'start_talking': {
      'en': 'Start talking to get help',
      'hi': 'मदद पाने के लिए बात करना शुरू करें',
      'mr': 'मदत मिळविण्यासाठी बोलणे सुरू करा',
      'ta': 'உதவி பெற பேசத் தொடங்குங்கள்',
    },
    'neural_link_active': {
      'en': 'NEURAL LINK ACTIVE',
      'hi': 'न्यूरल लिंक सक्रिय',
      'mr': 'न्यूरल लिंक सक्रिय',
      'ta': 'நரம்பியல் இணைப்பு செயலில்',
    },
    'speech_error': {
      'en': 'Speech Error',
      'hi': 'वाक् त्रुटि',
      'mr': 'स्पीच एरर',
      'ta': 'பேச்சு பிழை',
    },
    'ai_scanning': {
      'en': 'AI scanning in progress...',
      'hi': 'AI स्कैनिंग चल रही है...',
      'mr': 'AI स्कॅनिंग सुरू आहे...',
      'ta': 'AI ஸ்கேனிங் நடைபெறுகிறது...',
    },
    'scanning_failed': {
      'en': 'Scanning failed',
      'hi': 'स्कैनिंग विफल',
      'mr': 'स्कॅनिंग अयशस्वी',
      'ta': 'ஸ்கேனிங் தோல்வியடைந்தது',
    },
    'upload_success': {
      'en': 'Document uploaded successfully!',
      'hi': 'दस्तावेज़ सफलतापूर्वक अपलोड किया गया!',
      'mr': 'दस्तऐवज यशस्वीरित्या अपलोड केले!',
      'ta': 'ஆவணம் வெற்றிகரமாக பதிவேற்றப்பட்டது!',
    },
    'file_error': {
      'en': 'Error selecting file',
      'hi': 'फ़ाइल चुनने में त्रुटि',
      'mr': 'फाइल निवडताना त्रुटी',
      'ta': 'கோப்பைத் தேர்ந்தெடுப்பதில் பிழை',
    },
    'no_documents_found': {
      'en': 'No documents found',
      'hi': 'कोई दस्तावेज़ नहीं मिला',
      'mr': 'कोणतेही दस्तऐवज आढळले नाहीत',
      'ta': 'ஆவணங்கள் எதுவும் காணப்படவில்லை',
    },
    'no_archived_docs': {
      'en': 'No Archived Documents',
      'hi': 'कोई संग्रहीत दस्तावेज़ नहीं',
      'mr': 'संग्रहित दस्तऐवज नाहीत',
      'ta': 'எந்த காப்பக ஆவணங்களும் இல்லை',
    },
    'archived_hint': {
      'en': 'Archived documents will appear here',
      'hi': 'संग्रहीत दस्तावेज़ यहाँ दिखाई देंगे',
      'mr': 'संग्रहित दस्तऐवज येथे दिसतील',
      'ta': 'காப்பகப்படுத்தப்பட்ட ஆவணங்கள் இங்கே தோன்றும்',
    },
    'supported_formats': {
      'en': 'Supported Formats',
      'hi': 'समर्थित प्रारूप',
      'mr': 'समर्थित फॉर्म्यूट्स',
      'ta': 'ஆதரிக்கப்படும் வடிவங்கள்',
    },
    'no_conversations_yet': {
      'en': 'No conversations yet',
      'hi': 'अभी तक कोई बातचीत नहीं',
      'mr': 'अद्याप कोणतेही संभाषण नाही',
      'ta': 'உரையாடல்கள் இல்லை',
    },
    'start_asking': {
      'en': 'Start by asking CVI a question',
      'hi': 'CVI से प्रश्न पूछकर शुरुआत करें',
      'mr': 'CVI ला प्रश्न विचारून सुरुवात करा',
      'ta': 'CVI-இடம் கேள்வியைக் கேட்டுத் தொடங்குங்கள்',
    },
    'messages': {
      'en': 'messages',
      'hi': 'संदेश',
      'mr': 'संदेश',
      'ta': 'செய்திகள்',
    },
    'speech_not_available': {
      'en': 'Speech recognition not available on this device',
      'hi': 'इस डिवाइस पर वाक् पहचान उपलब्ध नहीं है',
      'mr': 'या डिव्हाइसवर स्पीच रिकग्निशन उपलब्ध नाही',
      'ta': 'இந்த சாதனத்தில் பேச்சு அங்கீகாரம் கிடைக்கவில்லை',
    },
    'init_failed': {
      'en': 'Failed to initialize voice engine',
      'hi': 'वॉयस इंजन शुरू करने में विफल',
      'mr': 'व्हॉइस इंजिन सुरू करण्यात अपयशी',
      'ta': 'குரல் இயந்திரத்தைத் தொடங்க முடியவில்லை',
    },
    'mic_permission_error': {
      'en': 'Microphone permission or service unavailable',
      'hi': 'माइक्रोफ़ोन अनुमति या सेवा अनुपलब्ध',
      'mr': 'मायक्रोफोन परवानगी किंवा सेवा अनुपलब्ध',
      'ta': 'மைக்ரோஃபோன் அனுமதி அல்லது சேவை கிடைக்கவில்லை',
    },
    'mic_unavailable': {
      'en': 'Microphone not available or permission denied',
      'hi': 'माइक्रोफ़ोन उपलब्ध नहीं है या अनुमति अस्वीकार कर दी गई है',
      'mr': 'मायक्रोफोन उपलब्ध नाही किंवा परवानगी नाकारली',
      'ta': 'மைக்ரோஃபோன் கிடைக்கவில்லை அல்லது அனுமதி மறுக்கப்பட்டது',
    },
    
    // Profile Extended
    'demographic_info': {
      'en': 'Demographic Information',
      'hi': 'जनसांख्यिकीय जानकारी',
      'mr': 'लोकसंख्याशास्त्रीय माहिती',
      'ta': 'மக்கள்தொகை தகவல்',
    },
    'age': {
      'en': 'Age',
      'hi': 'आयु',
      'mr': 'वय',
      'ta': 'வயது',
    },
    'annual_income': {
      'en': 'Annual Income',
      'hi': 'वार्षिक आय',
      'mr': 'वार्षिक उत्पन्न',
      'ta': 'ஆண்டு வருமானம்',
    },
    'occupation': {
      'en': 'Occupation',
      'hi': 'व्यवसाय',
      'mr': 'व्यवसाय',
      'ta': 'தொழில்',
    },
    'location': {
      'en': 'Location',
      'hi': 'स्थान',
      'mr': 'स्थान',
      'ta': 'இடம்',
    },
    'land_ownership': {
      'en': 'Land Ownership',
      'hi': 'भूमि स्वामित्व',
      'mr': 'जमीन मालकी',
      'ta': 'நில உரிமை',
    },
    'incomplete_profile': {
      'en': 'Incomplete Profile',
      'hi': 'अधूरा प्रोफ़ाइल',
      'mr': 'अपूर्ण प्रोफाइल',
      'ta': 'முழுமையற்ற சுயவிவரம்',
    },
    'complete_profile': {
      'en': 'Complete Profile',
      'hi': 'प्रोफ़ाइल पूर्ण करें',
      'mr': 'प्रोफाइल पूर्ण करा',
      'ta': 'சுயவிவரத்தை நிரப்பவும்',
    },
    'add_details_prompt': {
      'en': 'Add your details to get personalized scheme recommendations.',
      'hi': 'व्यक्तिगत योजना सिफारिशें प्राप्त करने के लिए अपना विवरण जोड़ें।',
      'mr': 'वैयक्तिकृत योजना शिफारशी मिळविण्यासाठी आपले तपशील जोडा.',
      'ta': 'தனிப்பயனாக்கப்பட்ட திட்ட பரிந்துரைகளைப் பெற உங்கள் விவரங்களைச் சேர்க்கவும்.',
    },
    'voice_notes': {
      'en': 'Voice Notes',
      'hi': 'वॉयस नोट्स',
      'mr': 'व्हॉइस नोट्स',
      'ta': 'குரல் குறிப்புகள்',
    },
    'family_members': {
      'en': 'Family Members',
      'hi': 'परिवार के सदस्य',
      'mr': 'कुटुंबातील सदस्य',
      'ta': 'குடும்ப உறுப்பினர்கள்',
    },
    'smart_queue': {
      'en': 'Smart Queue',
      'hi': 'स्मार्ट कतार',
      'mr': 'स्मार्ट रांग',
      'ta': 'ஸ்மார்ட் வரிசை',
    },
    'civic_progress': {
      'en': 'Civic Progress',
      'hi': 'नागरिक प्रगति',
      'mr': 'नागरी प्रगती',
      'ta': 'குடிமை முன்னேற்றம்',
    },
    'community_trust': {
      'en': 'Community Trust',
      'hi': 'सामुदायिक विश्वास',
      'mr': 'समुदाय विश्वास',
      'ta': 'சமூக நம்பிக்கை',
    },
    'emergency_mode': {
      'en': 'Emergency Mode',
      'hi': 'आपातकालीन मोड',
      'mr': 'आणीबाणी मोड',
      'ta': 'அவசரகால பயன்முறை',
    },
    'ar_guidance': {
      'en': 'AR Document Guidance',
      'hi': 'AR दस्तावेज़ मार्गदर्शन',
      'mr': 'AR दस्तऐवज मार्गदर्शन',
      'ta': 'AR ஆவண வழிகாட்டுதல்',
    },
    'verified_user': {
      'en': 'Verified User',
      'hi': 'सत्यापित उपयोगकर्ता',
      'mr': 'सत्यापित वापरकर्ता',
      'ta': 'சரிபார்க்கப்பட்ட பயனர்',
    },
    'unverified_account': {
      'en': 'Unverified Account',
      'hi': 'असत्यापित खाता',
      'mr': 'असत्यापित खाते',
      'ta': 'சரிபார்க்கப்படாத கணக்கு',
    },
    
    // Accessibility
    'accessibility_feature': {
      'en': 'Accessibility (Feature 11)',
      'hi': 'पहुंच (सुविधा 11)',
      'mr': 'प्रवेशयोग्यता (वैशिष्ट्य 11)',
      'ta': 'அணுகல்தன்மை (அம்சம் 11)',
    },
    'high_contrast': {
      'en': 'High Contrast Mode',
      'hi': 'हाई कंट्रास्ट मोड',
      'mr': 'उच्च कॉन्ट्रास्ट मोड',
      'ta': 'உயர் வேறுபாடு பயன்முறை',
    },
    'text_size': {
      'en': 'Text Size',
      'hi': 'टेक्स्ट का आकार',
      'mr': 'मजकुराचा आकार',
      'ta': 'உரை அளவு',
    },
    'color_blindness': {
      'en': 'Color Blindness',
      'hi': 'वर्णांधता',
      'mr': 'रंगांधळेपणा',
      'ta': 'வண்ணக் குருட்டுத்தன்மை',
    },
    'select_filter': {
      'en': 'Select Filter',
      'hi': 'फ़िल्टर चुनें',
      'mr': 'फिल्टर निवडा',
      'ta': 'வடிப்பான் தேர்ந்தெடுக்கவும்',
    },
    'none_normal_vision': {
      'en': 'None (Normal Vision)',
      'hi': 'कोई नहीं (सामान्य दृष्टि)',
      'mr': 'काहीही नाही (सामान्य दृष्टी)',
      'ta': 'எதுவும் இல்லை (சாதாரண பார்வை)',
    },
    'personalization_tip': {
      'en': 'Personalization Tip',
      'hi': 'वैयक्तिकरण सुझाव',
      'mr': 'वैयक्तिकरण टीप',
      'ta': 'தனிப்பயனாக்க குறிப்பு',
    },
    'complete_profile_tip': {
      'en': 'Complete your profile to see schemes and services recommended specifically for your eligibility.',
      'hi': 'अपनी पात्रता के अनुसार योजनाओं और सेवाओं की सिफारिशें देखने के लिए अपनी प्रोफ़ाइल पूरी करें।',
      'mr': 'तुमच्या पात्रतेनुसार योजना आणि सेवांच्या शिफारशी पाहण्यासाठी तुमचे प्रोफाइल पूर्ण करा।',
      'ta': 'உங்கள் தகுதிக்கு ஏற்ற திட்டங்கள் மற்றும் சேவைகளைப் பார்க்க உங்கள் சுயவிவரத்தை நிரப்பவும்.',
    },
    'setup_my_profile': {
      'en': 'Setup My Profile',
      'hi': 'मेरी प्रोफ़ाइल सेटअप करें',
      'mr': 'माझे प्रोफाइल सेटअप करा',
      'ta': 'என் சுயவிவரத்தை அமை',
    },
    'family': {
      'en': 'Family',
      'hi': 'परिवार',
      'mr': 'कुटुंब',
      'ta': 'குடும்பம்',
    },
    'high_priority_schemes': {
      'en': 'High-Priority Schemes',
      'hi': 'उच्च प्राथमिकता योजनाएं',
      'mr': 'उच्च प्राधान्य योजना',
      'ta': 'உயர் முன்னுரிமை திட்டங்கள்',
    },
    
    // Additional Dashboard
    'government_schemes': {
      'en': 'Government Schemes',
      'hi': 'सरकारी योजनाएं',
      'mr': 'सरकारी योजना',
      'ta': 'அரசு திட்டங்கள்',
    },
    'browse_schemes': {
      'en': 'Browse schemes by category',
      'hi': 'श्रेणी के अनुसार योजनाएं ब्राउज़ करें',
      'mr': 'वर्गानुसार योजना शोधा',
      'ta': 'வகை வாரியாக திட்டங்களை உலாவுக',
    },
    'family_hub': {
      'en': 'Family Hub',
      'hi': 'फॅमिली हब',
      'mr': 'फॅमिली हब',
      'ta': 'குடும்ப மையம்',
    },
    'sos_emergency': {
      'en': 'SOS Emergency',
      'hi': 'SOS आपातकाल',
      'mr': 'SOS आणीबाणी',
      'ta': 'SOS அவசரநிலை',
    },
    'trust_score': {
      'en': 'Trust Score',
      'hi': 'ट्रस्ट स्कोर',
      'mr': 'ट्रस्ट स्कोर',
      'ta': 'நம்பிக்கை மதிப்பெண்',
    },
    'recommended_for_you': {
      'en': 'Recommended for You',
      'hi': 'आपके लिए अनुशंसित',
      'mr': 'तुमच्यासाठी शिफारस केलेले',
      'ta': 'உங்களுக்கு பரிந்துரைக்கப்பட்டது',
    },
    'no_conversations_yet': {
      'en': 'No conversations yet',
      'hi': 'अभी तक कोई बातचीत नहीं',
      'mr': 'अद्याप संभाषण नाही',
      'ta': 'இதுவரை உரையாடல்கள் இல்லை',
    },
    'start_by_asking': {
      'en': 'Start by asking CVI a question',
      'hi': 'CVI से एक सवाल पूछकर शुरू करें',
      'mr': 'CVI ला प्रश्न विचारून सुरू करा',
      'ta': 'CVI இடம் கேள்வி கேட்டு தொடங்குங்கள்',
    },
    'messages': {
      'en': 'messages',
      'hi': 'संदेश',
      'mr': 'संदेश',
      'ta': 'செய்திகள்',
    },
    'in_progress': {
      'en': 'In Progress',
      'hi': 'प्रगति पर है',
      'mr': 'प्रगतीपथावर',
      'ta': 'செயலில் உள்ளது',
    },
    'hours_ago': {
      'en': 'hours ago',
      'hi': 'घंटे पहले',
      'mr': 'तासांपूर्वी',
      'ta': 'மணி நேரத்திற்கு முன்பு',
    },
    'days_ago': {
      'en': 'days ago',
      'hi': 'दिन पहले',
      'mr': 'दिवसांपूर्वी',
      'ta': 'நாட்களுக்கு முன்பு',
    },
    
    // Phone and Email
    'phone': {
      'en': 'Phone',
      'hi': 'फ़ोन',
      'mr': 'फोन',
      'ta': 'தொலைபேசி',
    },
    'email': {
      'en': 'Email',
      'hi': 'ईमेल',
      'mr': 'ईमेल',
      'ta': 'மின்னஞ்சல்',
    },
    'full_name': {
      'en': 'Full Name',
      'hi': 'पूरा नाम',
      'mr': 'पूर्ण नाव',
      'ta': 'முழு பெயர்',
    },
    'confirm_password': {
      'en': 'Confirm Password',
      'hi': 'पासवर्ड की पुष्टि करें',
      'mr': 'पासवर्ड पुष्टी करा',
      'ta': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    },
    'create_account': {
      'en': 'Create Account',
      'hi': 'खाता बनाएं',
      'mr': 'खाते तयार करा',
      'ta': 'கணக்கை உருவாக்கு',
    },
    'join_cvi': {
      'en': 'Join CVI',
      'hi': 'CVI में शामिल हों',
      'mr': 'CVI मध्ये सामील व्हा',
      'ta': 'CVI இல் சேரவும்',
    },
    'get_access': {
      'en': 'Get access to all civic services',
      'hi': 'सभी नागरिक सेवाओं तक पहुंच प्राप्त करें',
      'mr': 'सर्व नागरी सेवांमध्ये प्रवेश मिळवा',
      'ta': 'அனைத்து குடிமை சேவைகளையும் அணுகுங்கள்',
    },
    'terms_conditions': {
      'en': 'Terms & Conditions',
      'hi': 'नियम और शर्तें',
      'mr': 'अटी व शर्ती',
      'ta': 'விதிமுறைகள் & நிபந்தனைகள்',
    },
    'privacy_policy': {
      'en': 'Privacy Policy',
      'hi': 'गोपनीयता नीति',
      'mr': 'गोपनीयता धोरण',
      'ta': 'தனியுரிமைக் கொள்கை',
    },
    'i_agree_to': {
      'en': 'I agree to the',
      'hi': 'मैं सहमत हूं',
      'mr': 'मी सहमत आहे',
      'ta': 'நான் ஒப்புக்கொள்கிறேன்',
    },
    'already_have_account': {
      'en': 'Already have an account?',
      'hi': 'पहले से खाता है?',
      'mr': 'आधीपासून खाते आहे?',
      'ta': 'ஏற்கனவே கணக்கு உள்ளதா?',
    },
    'or_register_with': {
      'en': 'OR REGISTER WITH',
      'hi': 'या इसके साथ रजिस्टर करें',
      'mr': 'किंवा यासह नोंदणी करा',
      'ta': 'அல்லது இதனுடன் பதிவு செய்யவும்',
    },
    'eligible': {
      'en': 'ELIGIBLE',
      'hi': 'पात्र',
      'mr': 'पात्र',
      'ta': 'தகுதியுடையவர்',
    },
    'visit_official_website': {
      'en': 'Visit Official Website',
      'hi': 'आधिकारिक वेबसाइट पर जाएं',
      'mr': 'अधिकृत वेबसाइटला भेट द्या',
      'ta': 'அதிகாரப்பூர்வ வலைத்தளத்தைப் பார்வையிடவும்',
    },
    'about_service': {
      'en': 'About',
      'hi': 'के बारे में',
      'mr': 'बद्दल',
      'ta': 'பற்றி',
    },
    'online_application': {
      'en': 'Online Application',
      'hi': 'ऑनलाइन आवेदन',
      'mr': 'ऑनलाइन अर्ज',
      'ta': 'ஆன்லைன் விண்ணப்பம்',
    },
    'available': {
      'en': 'Available',
      'hi': 'उपलब्ध',
      'mr': 'उपलब्ध',
      'ta': 'கிடைக்கிறது',
    },
    'not_available': {
      'en': 'Not Available',
      'hi': 'उपलब्ध नहीं है',
      'mr': 'उपलब्ध नाही',
      'ta': 'கிடைக்கவில்லை',
    },
    'interactive_process_map': {
      'en': 'Interactive Process Map',
      'hi': 'इंटरएक्टिव प्रक्रिया मानचित्र',
      'mr': 'इंटरएक्टिव प्रक्रिया नकाशा',
      'ta': 'ஊடாடும் செயல்முறை வரைபடம்',
    },
    'eligibility_criteria': {
      'en': 'Eligibility Criteria',
      'hi': 'पात्रता मानदंड',
      'mr': 'पात्रता निकष',
      'ta': 'தகுதி வரம்பு',
    },
    'apply_now': {
      'en': 'Apply Now',
      'hi': 'अभी आवेदन करें',
      'mr': 'आता अर्ज करा',
      'ta': 'இப்பொழுதே விண்ணப்பிக்கவும்',
    },
    'track_application': {
      'en': 'Track Application',
      'hi': 'आवेदन ट्रैक करें',
      'mr': 'अर्जाचा मागोवा घ्या',
      'ta': 'விண்ணப்பத்தைக் கண்காணிக்கவும்',
    },
    'requires': {
      'en': 'Requires',
      'hi': 'आवश्यक',
      'mr': 'आवश्यक',
      'ta': 'தேவைப்படுகிறது',
    },
    'download_official_form': {
      'en': 'Download Official Form',
      'hi': 'आधिकारिक फॉर्म डाउनलोड करें',
      'mr': 'अधिकृत फॉर्म डाउनलोड करा',
      'ta': 'அதிகாரப்பூர்வ படிவத்தைப் பதிவிறக்கவும்',
    },
    'unlock_eligibility_msg': {
      'en': 'Complete your profile to unlock eligibility checking!',
      'hi': 'पात्रता जांच अनलॉक करने के लिए अपनी प्रोफ़ाइल पूरी करें!',
      'mr': 'पात्रता तपासणी अनलॉक करण्यासाठी आपले प्रोफाइल पूर्ण करा!',
      'ta': 'தகுதி சரிபார்ப்பைத் திறக்க உங்கள் சுயவிவரத்தை நிரப்பவும்!',
    },
    'tell_us_about_yourself': {
      'en': 'Tell us about yourself',
      'hi': 'अपने बारे में बताएं',
      'mr': 'आम्हाला तुमच्याबद्दल सांगा',
      'ta': 'உங்களைப் பற்றி எங்களிடம் கூறுங்கள்',
    },
    'personalize_civic_msg': {
      'en': 'Help us personalize your civic experience and find the best schemes for you.',
      'hi': 'अपने नागरिक अनुभव को व्यक्तिगत बनाने और आपके लिए सर्वोत्तम योजनाएं खोजने में हमारी सहायता करें।',
      'mr': 'तुमचा नागरी अनुभव वैयक्तिकृत करण्यात आणि तुमच्यासाठी सर्वोत्तम योजना शोधण्यात आम्हाला मदत करा.',
      'ta': 'உங்கள் குடிமை அனுபவத்தைத் தனிப்பயனாக்கவும் உங்களுக்கான சிறந்த திட்டங்களைக் கண்டறியவும் எங்களுக்கு உதவுங்கள்.',
    },
    'how_old_are_you': {
      'en': 'How old are you?',
      'hi': 'आपकी उम्र क्या है?',
      'mr': 'तुमचे वय किती आहे?',
      'ta': 'உங்கள் வயது என்ன?',
    },
    'what_is_your_income': {
      'en': 'What is your annual family income?',
      'hi': 'आपकी वार्षिक पारिवारिक आय क्या है?',
      'mr': 'तुमचे वार्षिक कौटुंबिक उत्पन्न किती आहे?',
      'ta': 'உங்கள் குடும்பத்தின் ஆண்டு வருமானம் என்ன?',
    },
    'slider_increment_note': {
      'en': 'Slider moves in increments of 10k',
      'hi': 'स्लाइडर 10k की वृद्धि में चलता है',
      'mr': 'स्लायडर 10k च्या पटीत हलतो',
      'ta': 'ஸ்லைடர் 10k அதிகரிப்புகளில் நகர்கிறது',
    },
    'what_is_your_occupation': {
      'en': 'What is your occupation?',
      'hi': 'आपका व्यवसाय क्या है?',
      'mr': 'तुमचा व्यवसाय काय आहे?',
      'ta': 'உங்கள் தொழில் என்ன?',
    },
    'where_do_you_live': {
      'en': 'Where do you live?',
      'hi': 'आप कहां रहते हैं?',
      'mr': 'तुम्ही कुठे राहता?',
      'ta': 'நீங்கள் எங்கு வசிக்கிறீர்கள்?',
    },
    'own_land_q': {
      'en': 'Do you own agricultural land?',
      'hi': 'क्या आपके पास कृषि भूमि है?',
      'mr': 'तुमच्याकडे शेतजमीन आहे का?',
      'ta': 'உங்களுக்கு விவசாய நிலம் உள்ளதா?',
    },
    'farmer_scheme_note': {
      'en': 'Required for some farmer schemes',
      'hi': 'कुछ किसान योजनाओं के लिए आवश्यक',
      'mr': 'काही शेतकरी योजनांसाठी आवश्यक',
      'ta': 'சில விவசாயி திட்டங்களுக்கு தேவை',
    },
    'save_profile': {
      'en': 'Save Profile',
      'hi': 'प्रोफ़ाइल सहेजें',
      'mr': 'प्रोफाइल सेव्ह करा',
      'ta': 'சுயவிவரத்தைச் சேமி',
    },
    'student': {
      'en': 'Student',
      'hi': 'छात्र',
      'mr': 'विद्यार्थी',
      'ta': 'மாணவர்',
    },
    'self_employed': {
      'en': 'Self-Employed',
      'hi': 'स्व-नियोजित',
      'mr': 'स्वयंरोजगार',
      'ta': 'சுயதொழில்',
    },
    'farmer': {
      'en': 'Farmer',
      'hi': 'किसान',
      'mr': 'शेतकरी',
      'ta': 'விவசாயி',
    },
    'govt_employee': {
      'en': 'Govt Employee',
      'hi': 'सरकारी कर्मचारी',
      'mr': 'सरकारी कर्मचारी',
      'ta': 'அரசு ஊழியர்',
    },
    'private_sector': {
      'en': 'Private Sector',
      'hi': 'निजी क्षेत्र',
      'mr': 'खाजगी क्षेत्र',
      'ta': 'தனியார் துறை',
    },
    'retired': {
      'en': 'Retired',
      'hi': 'सेवानिवृत्त',
      'mr': 'निवृत्त',
      'ta': 'ஓய்வு பெற்றவர்',
    },
    'unemployed': {
      'en': 'Unemployed',
      'hi': 'बेरोज़गार',
      'mr': 'बेरोजगार',
      'ta': 'வேலையில்லாதவர்',
    },
    'urban': {
      'en': 'Urban',
      'hi': 'शहरी',
      'mr': 'शहरी',
      'ta': 'நகர்ப்புறம்',
    },
    'semi_urban': {
      'en': 'Semi-Urban',
      'hi': 'अर्ध-शहरी',
      'mr': 'निमशहरी',
      'ta': 'பாதி நகர்ப்புறம்',
    },
    'rural': {
      'en': 'Rural',
      'hi': 'ग्रामीण',
      'mr': 'ग्रामीण',
      'ta': 'கிராமப்புறம்',
    },
    'already_applied': {
      'en': 'Already Applied',
      'hi': 'पहले से लागू',
      'mr': 'आधीच अर्ज केला आहे',
      'ta': 'ஏற்கனவே விண்ணப்பிக்கப்பட்டது',
    },
    'application_submitted': {
      'en': 'Application Submitted Successfully!',
      'hi': 'आवेदन सफलतापूर्वक जमा किया गया!',
      'mr': 'अर्ज यशस्वीरित्या सादर केला!',
      'ta': 'விண்ணப்பம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
    },
    'no_activity_yet': {
      'en': 'No recent activity yet',
      'hi': 'अभी तक कोई हालिया गतिविधि नहीं',
      'mr': 'अद्याप कोणतीही अलीकडील क्रियाकलाप नाही',
      'ta': 'இன்னும் சமீபத்திய செயல்பாடுகள் இல்லை',
    },
    'submitted': {
      'en': 'Submitted',
      'hi': 'जमा किया गया',
      'mr': 'सादर केले',
      'ta': 'சமர்ப்பிக்கப்பட்டது',
    },
    'verified': {
      'en': 'Verified',
      'hi': 'सत्यापित',
      'mr': 'सत्यापित',
      'ta': 'சரிபார்க்கப்பட்டது',
    },
    'approved': {
      'en': 'Approved',
      'hi': 'स्वीकृत',
      'mr': 'मंजूर',
      'ta': 'அங்கீகரிக்கப்பட்டது',
    },
    'family_dashboard': {
      'en': 'Family Dashboard',
      'hi': 'फैमिली डैशबोर्ड',
      'mr': 'फॅमिली डॅशबोर्ड',
      'ta': 'குடும்ப டாஷ்போர்டு',
    },
    'no_family_members': {
      'en': 'No family members yet',
      'hi': 'अभी तक परिवार का कोई सदस्य नहीं है',
      'mr': 'अद्याप कुटुंबातील कोणताही सदस्य नाही',
      'ta': 'இன்னும் குடும்ப உறுப்பினர்கள் இல்லை',
    },
    'add_members_msg': {
      'en': 'Add members to find schemes for them',
      'hi': 'योजनाएं खोजने के लिए सदस्यों को जोड़ें',
      'mr': 'योजना शोधण्यासाठी सदस्यांना जोडा',
      'ta': 'அவர்களுக்கான திட்டங்களைக் கண்டறிய உறுப்பினர்களைச் சேர்க்கவும்',
    },
    'add_member': {
      'en': 'Add Member',
      'hi': 'सदस्य जोड़ें',
      'mr': 'सदस्य जोडा',
      'ta': 'உறுப்பினரைச் சேர்க்கவும்',
    },
    'dependent': {
      'en': 'Dependent',
      'hi': 'आश्रित',
      'mr': 'अवलंबून',
      'ta': 'சார்ந்திருப்பவர்',
    },
    'spouse': {
      'en': 'Spouse',
      'hi': 'जीवनसाथी',
      'mr': 'जोडीदार',
      'ta': 'மனைவி/கணவர்',
    },
    'child': {
      'en': 'Child',
      'hi': 'बच्चा',
      'mr': 'मूल',
      'ta': 'குழந்தை',
    },
    'father': {
      'en': 'Father',
      'hi': 'पिता',
      'mr': 'पिता',
      'ta': 'தந்தை',
    },
    'mother': {
      'en': 'Mother',
      'hi': 'माता',
      'mr': 'माता',
      'ta': 'தாய்',
    },
    'sibling': {
      'en': 'Sibling',
      'hi': 'भाई-बहन',
      'mr': 'भाऊ-बहीण',
      'ta': 'உடன் பிறந்தவர்',
    },
    'relation': {
      'en': 'Relation',
      'hi': 'रिश्ता',
      'mr': 'नाते',
      'ta': 'உறவு',
    },
    'cancel': {
      'en': 'Cancel',
      'hi': 'रद्द करें',
      'mr': 'रद्द करा',
      'ta': 'ரத்து செய்',
    },
    'add': {
      'en': 'Add',
      'hi': 'जोड़ें',
      'mr': 'जोडा',
      'ta': 'சேர்',
    },
    'skip_the_line': {
      'en': 'Skip the Line',
      'hi': 'लाइन छोड़ें',
      'mr': 'लाइन सोडून द्या',
      'ta': 'வரிசையைத் தவிர்க்கவும்',
    },
    'get_token': {
      'en': 'Get Token',
      'hi': 'टोकन प्राप्त करें',
      'mr': 'टोकन मिळवा',
      'ta': 'டோக்கன் பெறுக',
    },
    'your_token': {
      'en': 'YOUR TOKEN',
      'hi': 'आपका टोकन',
      'mr': 'तुमचा टोकन',
      'ta': 'உங்கள் டோக்கன்',
    },
    'serving': {
      'en': 'Serving',
      'hi': 'सेवारत',
      'mr': 'चालू आहे',
      'ta': 'சேவையில் உள்ளது',
    },
    'wait_time': {
      'en': 'Wait Time',
      'hi': 'इंतजार का समय',
      'mr': 'प्रतीक्षा वेळ',
      'ta': 'காத்திருப்பு நேரம்',
    },
    'cancel_token': {
      'en': 'Cancel Token',
      'hi': 'टोकन रद्द करें',
      'mr': 'टोकन रद्द करा',
      'ta': 'டோக்கனை ரத்துசெய்',
    },
    'emergency_mode': {
      'en': 'EMERGENCY MODE',
      'hi': 'आपातकालीन मोड',
      'mr': 'आणीबाणी मोड',
      'ta': 'அவசர நிலை',
    },
    'tap_for_112': {
      'en': 'TAP FOR 112',
      'hi': '112 के लिए टैप करें',
      'mr': '112 साठी टॅप करा',
      'ta': '112 ஐ அழைக்கவும்',
    },
    'your_coordinates': {
      'en': 'YOUR COORDINATES',
      'hi': 'आपका स्थान',
      'mr': 'तुमचे स्थान',
      'ta': 'உங்கள் இருப்பிடம்',
    },
    'location_unavailable': {
      'en': 'Location Unavailable',
      'hi': 'स्थान अनुपलब्ध',
      'mr': 'स्थान उपलब्ध नाही',
      'ta': 'இருப்பிடம் கிடைக்கவில்லை',
    },
    'offline_guides': {
      'en': 'Offline Guides',
      'hi': 'ऑफलाइन गाइड',
      'mr': 'ऑफलाइन मार्गदर्शक',
      'ta': 'ஆஃப்லைன் வழிகாட்டிகள்',
    },
    'community_trust': {
      'en': 'Community Trust',
      'hi': 'सामुदायिक विश्वास',
      'mr': 'सामुदायिक विश्वास',
      'ta': 'சமூக நம்பிக்கை',
    },
    'vouch_explanation': {
      'en': 'Help trusted community members get access to services by acting as a witness. Your "Vouch" counts as a digital signature.',
      'hi': 'गवाह के रूप में कार्य करके भरोसेमंद सामुदायिक सदस्यों को सेवाओं तक पहुँच प्राप्त करने में सहायता करें। आपका "वाउच" एक डिजिटल हस्ताक्षर के रूप में गिना जाता है।',
      'mr': 'साक्षीदार म्हणून काम करून विश्वासू समुदाय सदस्यांना सेवांमध्ये प्रवेश मिळवून देण्यास मदत करा. तुमचे "वाउच" डिजिटल स्वाक्षरी म्हणून गणले जाते.',
      'ta': 'சாட்சியாக செயல்படுவதன் மூலம் நம்பகமான சமூக உறுப்பினர்களுக்கு சேவைகளுக்கான அணுகலைப் பெற உதவுங்கள். உங்கள் "வாவுச்" டிஜிட்டல் கையொப்பமாகக் கருதப்படுகிறது.',
    },
    'pending_verifications': {
      'en': 'Pending Verifications',
      'hi': 'लंबित सत्यापन',
      'mr': 'प्रलंबित पडताळणी',
      'ta': 'நிலுவையில் உள்ள சரிபார்ப்புகள்',
    },
    'vouch': {
      'en': 'Vouch for this person',
      'hi': 'इस व्यक्ति के लिए गवाही दें',
      'mr': 'या व्यक्तीसाठी पुष्टी करा',
      'ta': 'இந்த நபருக்கு சான்று அளிக்கவும்',
    },
    'verification_complete': {
      'en': 'Verification Complete',
      'hi': 'सत्यापन पूर्ण',
      'mr': 'पडताळणी पूर्ण झाली',
      'ta': 'சரிபார்ப்பு முடிந்தது',
    },
    'queries': {
      'en': 'Queries',
      'hi': 'सवाल',
      'mr': 'प्रश्न',
      'ta': 'கேள்விகள்',
    },
    'success': {
      'en': 'Success',
      'hi': 'सफलता',
      'mr': 'यश',
      'ta': 'வெற்றி',
    },
    'pending': {
      'en': 'Pending',
      'hi': 'लंबित',
      'mr': 'प्रलंबित',
      'ta': 'நிலுவையில்',
    },
    'avg_time': {
      'en': 'Avg. Time',
      'hi': 'औसत समय',
      'mr': 'सरासरी वेळ',
      'ta': 'சராசரி நேரம்',
    },
    'welcome_back': {
      'en': 'Welcome back',
      'hi': 'वापसी पर स्वागत है',
      'mr': 'पुनरागमन केल्याबद्दल स्वागत',
      'ta': 'மீண்டும் வருக',
    },
    'messages': {
      'en': 'messages',
      'hi': 'संदेश',
      'mr': 'संदेश',
      'ta': 'செய்திகள்',
    },
    'no_conversations_yet': {
      'en': 'No conversations yet',
      'hi': 'अभी तक कोई बातचीत नहीं हुई है',
      'mr': 'अद्याप कोणतेही संभाषण नाही',
      'ta': 'இன்னும் உரையாடல்கள் எதுவும் இல்லை',
    },
    'start_asking': {
      'en': 'Tap the mic and start asking!',
      'hi': 'माइक टैप करें और पूछना शुरू करें!',
      'mr': 'माईक टॅप करा आणि विचारायला सुरुवात करा!',
      'ta': 'மைக்ரோபோனைத் தட்டி கேட்கத் தொடங்குங்கள்!',
    },
    'start_conversation': {
      'en': 'Start Conversation',
      'hi': 'बातचीत शुरू करें',
      'mr': 'संभाषण सुरू करा',
      'ta': 'உரையாடலைத் தொடங்குங்கள்',
    },
    'continue_conversation': {
      'en': 'Continue Conversation',
      'hi': 'बातचीत जारी रखें',
      'mr': 'संभाषण सुरू ठेवा',
      'ta': 'உரையாடலைத் தொடரவும்',
    },
    'recent_activity': {
      'en': 'Recent Activity',
      'hi': 'हालिया गतिविधि',
      'mr': 'अलीकडील क्रियाकलाप',
      'ta': 'சமீபத்திய செயல்பாடு',
    },
    'view_all': {
      'en': 'View All',
      'hi': 'सभी देखें',
      'mr': 'सर्व पहा',
      'ta': 'அனைத்தையும் பார்',
    },
    'personalization_tip': {
      'en': 'Personalization Tip',
      'hi': 'निजीकरण टिप',
      'mr': 'वैयक्तिकरण टीप',
      'ta': 'தனிப்பயனாக்க உதவிக்குறிப்பு',
    },
    'complete_profile_tip': {
      'en': 'Complete your profile to get personalized recommendations and check eligibility.',
      'hi': 'व्यक्तिगत सिफारिशें प्राप्त करने और पात्रता जांचने के लिए अपनी प्रोफ़ाइल पूरी करें।',
      'mr': 'वैयक्तिकृत शिफारसी मिळवण्यासाठी आणि पात्रता तपासण्यासाठी तुमचे प्रोफाइल पूर्ण करा.',
      'ta': 'தனிப்பயனாக்கப்பட்ட பரிந்துரைகளைப் பெறவும் தகுதியைச் சரிபார்க்கவும் உங்கள் சுயவிவரத்தைப் பூர்த்தி செய்யவும்.',
    },
    'setup_my_profile': {
      'en': 'Setup My Profile',
      'hi': 'मेरी प्रोफ़ाइल सेट करें',
      'mr': 'माझे प्रोफाइल सेट करा',
      'ta': 'எனது சுயவிவரத்தை அமைக்கவும்',
    },
    'recommended_for_you': {
      'en': 'Recommended for You',
      'hi': 'आपके लिए अनुशंसित',
      'mr': 'तुमच्यासाठी शिफारस केलेले',
      'ta': 'உங்களுக்காக பரிந்துரைக்கப்படுகிறது',
    },
    'government_schemes': {
      'en': 'Government Schemes',
      'hi': 'सरकारी योजनाएं',
      'mr': 'सरकारी योजना',
      'ta': 'அரசு திட்டங்கள்',
    },
    'browse_schemes': {
      'en': 'Browse and search for all schemes',
      'hi': 'सभी योजनाओं को ब्राउज़ करें और खोजें',
      'mr': 'सर्व योजना ब्राउझ करा आणि शोधा',
      'ta': 'அனைத்து திட்டங்களையும் தேடவும் மற்றும் கண்டறியவும்',
    },
    'recent_conversation': {
      'en': 'Recent Conversation',
      'hi': 'हालिया बातचीत',
      'mr': 'अलीकडील संभाषण',
      'ta': 'சமீபத்திய உரையாடல்',
    },
    'ask_cvi': {
      'en': 'Ask CVI',
      'hi': 'CVI से पूछें',
      'mr': 'CVI ला विचारा',
      'ta': 'CVI-யிடம் கேளுங்கள்',
    },
    'smart_queue': {
      'en': 'Smart Queue',
      'hi': 'स्मार्ट कतार',
      'mr': 'स्मार्ट क्यू',
      'ta': 'ஸ்மார்ட் வரிசை',
    },
    'family_hub': {
      'en': 'Family Hub',
      'hi': 'फैमिली हब',
      'mr': 'फॅमिली हब',
      'ta': 'குடும்ப மையம்',
    },
    'sos_emergency': {
      'en': 'SOS Emergency',
      'hi': 'एसओएस आपातकाल',
      'mr': 'एसओएस आणीबाणी',
      'ta': 'SOS அவசரநிலை',
    },
    'trust_score': {
      'en': 'Trust Score',
      'hi': 'ट्रस्ट स्कोर',
      'mr': 'ट्रस्ट स्कोअर',
      'ta': 'நம்பிக்கை மதிப்பீடு',
    },
    'high_priority_schemes': {
      'en': 'High Priority Services',
      'hi': 'उच्च प्राथमिकता सेवाएं',
      'mr': 'उच्च प्राधान्य सेवा',
      'ta': 'உயர் முன்னுரிமை சேவைகள்',
    },
  };

  static String get(String key, String languageCode) {
    if (translations.containsKey(key)) {
      return translations[key]![languageCode] ?? translations[key]!['en'] ?? key;
    }
    return key;
  }
}
